# Generated by Django 5.2 on 2025-04-06 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_auto_20250405_0604'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='ratingAuthor',
            new_name='rating_author',
        ),
        migrations.RemoveField(
            model_name='author',
            name='AuthorUser',
        ),
        migrations.AddField(
            model_name='author',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
